version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-station
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: station
    volumes:
      - ./data:/data/db
    command: mongod --noauth