cloud:
  gateway:
    routes:
        ##vehicule
      - id: vehicule-service
        uri: lb://vehicule-service
        predicates:
          - Path=/vehicules/**
        # filters:
        #   - StripPrefix=1
        ##station
      - id: station-service
        uri: lb://station-service
        predicates:
          - Path=/stations/**
        # filters:
        #   - StripPrefix=1
        ##user
      - id: utilisateur-service
        uri: lb://utilisateur-service
        predicates:
          - Path=/utilisateurs/**
        # filters:
        #   - StripPrefix=1
        #rental
      - id: rental-service
        uri: lb://rental-service
        predicates:
          - Path=/rentals/**
        # filters:
        #   - StripPrefix=1
      - id: statistics-service
        uri: lb://statistics-service
        predicates:
          - Path=/statistics/**
        # filters:
        #   - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}


