version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-rental
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_DATABASE: rental
    volumes:
      - ./data:/data/db
    command: mongod --noauth


