version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb-utilisateur
    ports:
        - "27019:27017"
    environment:
        MONGO_INITDB_DATABASE: utilisateur
    volumes:
        - ./data:/data/db
    command: mongod --noauth